# This file was generated by protoc-gen-elixir (grpc plugin) from
# priv/protos/hyper/grpc/v1/machines.proto and is checked in.
# Regenerate with: mix proto.gen (see README "gRPC" section). Do not edit by hand.
defmodule Hyper.Grpc.V1.Machines.Service do
  @moduledoc false

  use GRPC.Service, name: "hyper.grpc.v1.Machines", protoc_gen_elixir_version: "0.17.0"

  rpc(:CreateMachine, Hyper.Grpc.V1.CreateMachineRequest, Hyper.Grpc.V1.CreateMachineResponse)

  rpc(:StopMachine, Hyper.Grpc.V1.StopMachineRequest, Hyper.Grpc.V1.StopMachineResponse)

  rpc(:GetMachine, Hyper.Grpc.V1.GetMachineRequest, Hyper.Grpc.V1.GetMachineResponse)

  rpc(:ListMachines, Hyper.Grpc.V1.ListMachinesRequest, Hyper.Grpc.V1.ListMachinesResponse)
end

defmodule Hyper.Grpc.V1.Machines.Stub do
  @moduledoc false

  use GRPC.Stub, service: Hyper.Grpc.V1.Machines.Service
end
