# This file was generated by protoc-gen-elixir from
# priv/protos/hyper/grpc/v1/machines.proto and is checked in.
# Regenerate with: mix proto.gen (see README "gRPC" section). Do not edit by hand.
defmodule Hyper.Grpc.V1.InstanceType do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :INSTANCE_TYPE_UNSPECIFIED, 0
  field :INSTANCE_TYPE_MICRO, 1
  field :INSTANCE_TYPE_MILLI, 2
  field :INSTANCE_TYPE_CENTI, 3
  field :INSTANCE_TYPE_DECI, 4
  field :INSTANCE_TYPE_BASE, 5
  field :INSTANCE_TYPE_DECA, 6
  field :INSTANCE_TYPE_HECTO, 7
  field :INSTANCE_TYPE_KILO, 8
  field :INSTANCE_TYPE_MEGA, 9
  field :INSTANCE_TYPE_GIGA, 10
  field :INSTANCE_TYPE_TERA, 11
end

defmodule Hyper.Grpc.V1.Architecture do
  @moduledoc false

  use Protobuf, enum: true, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :ARCHITECTURE_UNSPECIFIED, 0
  field :ARCHITECTURE_X86_64, 1
  field :ARCHITECTURE_AARCH64, 2
end

defmodule Hyper.Grpc.V1.CreateMachineRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :img_id, 1, type: :string, json_name: "imgId"
  field :instance_type, 2, type: Hyper.Grpc.V1.InstanceType, enum: true, json_name: "instanceType"
  field :arch, 3, type: Hyper.Grpc.V1.Architecture, enum: true
  field :boot_args, 4, type: :string, json_name: "bootArgs"
end

defmodule Hyper.Grpc.V1.CreateMachineResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :vm_id, 1, type: :string, json_name: "vmId"
  field :node, 2, type: :string
end

defmodule Hyper.Grpc.V1.StopMachineRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :vm_id, 1, type: :string, json_name: "vmId"
end

defmodule Hyper.Grpc.V1.StopMachineResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3
end

defmodule Hyper.Grpc.V1.GetMachineRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :vm_id, 1, type: :string, json_name: "vmId"
end

defmodule Hyper.Grpc.V1.GetMachineResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :vm_id, 1, type: :string, json_name: "vmId"
  field :node, 2, type: :string
end

defmodule Hyper.Grpc.V1.ListMachinesRequest do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3
end

defmodule Hyper.Grpc.V1.ListMachinesResponse do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :machines, 1, repeated: true, type: Hyper.Grpc.V1.Machine
end

defmodule Hyper.Grpc.V1.Machine do
  @moduledoc false

  use Protobuf, protoc_gen_elixir_version: "0.17.0", syntax: :proto3

  field :vm_id, 1, type: :string, json_name: "vmId"
  field :node, 2, type: :string
end
